### ISSUE TITLE
Globbing not working for "getsamplesummary.py"

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/data-delivery#10]
I'm not getting the script to work with how the current glob is set up. I think it has  I don't find any results for:

```
$ ll /mnt/hds/proj/bioinfo/DEMUX/*HBDPAADXX*/Unalign*/Project_*/Sample_*SIB923A1[BF]_*
```

... but if you run the glob with this string you do get results:

```
$ ll /mnt/hds/proj/bioinfo/DEMUX/*HBDPAADXX*/Unalign*/Project_*/Sample_*SIB923A1_*
```

The result is that no fastq files get symlinked

**Comment by robinandeer** [comment]
Will it work with just a simple ``*``?

```python
"{demuxdir}*{fc}*/Unalign*/Project_*/Sample_*{sample_name}*_*/*L00{lane}*gz"
```

**Comment by ingkebil** [comment]
I checked and it should indeed just work with what you suggested.

The only issue I can see is in the odd case a sample hasn't been pushed through LIMS and would be sequenced with its external ID, matching might not be restrictive enough. e.g. sample named '1' will most likely match a bit too much at that point.

I'll use your solution for now.
